In [1]:
import pandas as pd

In [2]:
matches_df = pd.read_csv("../data/data_final.csv")

In [3]:
matches_df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,referee,match report,notes,sh,sot,dist,pk,pkatt,season,club
0,1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,...,Michael Oliver,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,2023,Manchester-City
1,2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,...,David Coote,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,2023,Manchester-City
2,3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,...,Jarred Gillett,Match Report,NaN,21.0,10.0,16.2,0.0,0.0,2023,Manchester-City
3,4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,...,Darren England,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,2023,Manchester-City
4,5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,...,Paul Tierney,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,2023,Manchester-City

In [4]:
matches_df.shape

(2101, 27)

In [5]:
matches_df["club"].value_counts()

Southampton                 108
Arsenal                     107
Everton                     106
Chelsea                     105
Fulham                       74
Liverpool                    73
Newcastle United             72
West Ham United              72
Manchester United            72
Brighton and Hove Albion     72
Leeds United                 71
Burnley                      71
Wolverhampton Wanderers      71
Tottenham Hotspur            71
Manchester City              71
Crystal Palace               71
Leicester City               70
Brentford                    70
Aston Villa                  70
Sheffield United             38
West Bromwich Albion         38
Leeds-United                 36
Nottingham-Forest            36
Bournemouth                  36
Wolverhampton-Wanderers      36
Crystal-Palace               36
Aston-Villa                  36
Tottenham-Hotspur            36
West-Ham-United              36
Manchester-City              35
Manchester-United            35
Newcastle-United             35
Leicester-City               35
Brighton-and-Hove-Albion     34
Watford                      33
Norwich City                 33
Name: club, dtype: int64

In [6]:
for i in range(2101):
    name = matches_df[matches_df.columns[-1]][i]
    name = " ".join(name.split("-"))
    matches_df.replace(to_replace = matches_df[matches_df.columns[-1]][i], value = name, inplace = True)

In [7]:
matches_df["club"].value_counts()

Southampton                 108
West Ham United             108
Wolverhampton Wanderers     107
Crystal Palace              107
Newcastle United            107
Manchester United           107
Leeds United                107
Tottenham Hotspur           107
Arsenal                     107
Everton                     106
Manchester City             106
Aston Villa                 106
Brighton and Hove Albion    106
Chelsea                     105
Leicester City              105
Fulham                       74
Liverpool                    73
Burnley                      71
Brentford                    70
West Bromwich Albion         38
Sheffield United             38
Bournemouth                  36
Nottingham Forest            36
Watford                      33
Norwich City                 33
Name: club, dtype: int64

In [8]:
matches_df["date"] = pd.to_datetime(matches_df["date"])

In [10]:
matches_df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,referee,match report,notes,sh,sot,dist,pk,pkatt,season,club
0,1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,...,Michael Oliver,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,2023,Manchester City
1,2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,...,David Coote,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,2023,Manchester City
2,3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,...,Jarred Gillett,Match Report,NaN,21.0,10.0,16.2,0.0,0.0,2023,Manchester City
3,4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,...,Darren England,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,2023,Manchester City
4,5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,...,Paul Tierney,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,2023,Manchester City

One-hot encoding the columns

In [11]:
matches_df["venue_code"] = matches_df["venue"].astype("category").cat.codes

In [12]:
matches_df["opp_code"] = matches_df["opponent"].astype("category").cat.codes

In [13]:
matches_df["club_code"] = matches_df["club"].astype("category").cat.codes

In [ ]:
matches_df["hour"] = matches_df["time"].str.replace(":.+", "", regex=True).astype("int")

In [ ]:
matches_df["day_code"] = matches_df["date"].dt.dayofweek

In [14]:
matches_df["target"] = (matches_df["result"] == "W").astype("int")

In [16]:
matches_df.drop(matches_df.columns[[0]], axis = 1, inplace = True)

In [17]:
matches_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sot,dist,pk,pkatt,season,club,venue_code,opp_code,club_code,target
0,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,1.0,18.7,1.0,1.0,2023,Manchester City,0,23,13,1
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,7.0,17.5,0.0,0.0,2023,Manchester City,1,2,13,1
2,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,10.0,16.2,0.0,0.0,2023,Manchester City,0,15,13,0
3,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,5.0,14.1,0.0,0.0,2023,Manchester City,1,7,13,1
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,9.0,14.8,0.0,0.0,2023,Manchester City,1,17,13,1

In [18]:
matches_df.isna().sum()

date               0
time               0
comp               0
round              0
day                0
venue              0
result             0
gf                 0
ga                 0
opponent           0
xg                 0
xga                0
poss               0
attendance       700
captain            0
formation          0
referee            0
match report       0
notes           2101
sh                 0
sot                0
dist               1
pk                 0
pkatt              0
season             0
club               0
venue_code         0
opp_code           0
club_code          0
target             0
dtype: int64

## Random Forest Algorithm

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [21]:
train = matches_df[matches_df["date"] < '2023-01-01']

In [22]:
test = matches_df[matches_df["date"] > '2023-01-01']

In [23]:
predictors = ["venue_code", "opp_code", "club_code"]

In [24]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [25]:
predictions = rf.predict(test[predictors])

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
accuracy_score(test["target"], predictions)

0.6394736842105263

In [28]:
combined_df = pd.DataFrame(dict(actual=test["target"], prediction=predictions))

In [29]:
pd.crosstab(index=combined_df["actual"], columns=combined_df["prediction"])

prediction    0   1
actual
0           184  47
1            90  59

In [30]:
from sklearn.metrics import precision_score

In [31]:
precision_score(test["target"], predictions)

0.5566037735849056

In [32]:
grouped_matches = matches_df.groupby("club")

In [33]:
group = grouped_matches.get_group("Manchester United").sort_values("date")

In [34]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,sot,dist,pk,pkatt,season,club,venue_code,opp_code,club_code,target
1379,2020-09-19,17:30,Premier League,Matchweek 2,Sat,Home,L,1.0,3.0,Crystal Palace,...,4.0,18.9,0.0,0.0,2021,Manchester United,1,7,14,0
1380,2020-09-26,12:30,Premier League,Matchweek 3,Sat,Away,W,3.0,2.0,Brighton,...,2.0,17.8,1.0,1.0,2021,Manchester United,0,4,14,1
1381,2020-10-04,16:30,Premier League,Matchweek 4,Sun,Home,L,1.0,6.0,Tottenham,...,1.0,22.7,1.0,1.0,2021,Manchester United,1,20,14,0
1382,2020-10-17,20:00,Premier League,Matchweek 5,Sat,Away,W,4.0,1.0,Newcastle Utd,...,11.0,19.5,0.0,1.0,2021,Manchester United,0,15,14,1
1383,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Home,D,0.0,0.0,Chelsea,...,4.0,16.9,0.0,0.0,2021,Manchester United,1,6,14,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,2023-04-27,20:15,Premier League,Matchweek 33,Thu,Away,D,2.0,2.0,Tottenham,...,7.0,17.9,0.0,0.0,2023,Manchester United,0,20,14,0
137,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Home,W,1.0,0.0,Aston Villa,...,6.0,19.0,0.0,0.0,2023,Manchester United,1,1,14,1
138,2023-05-04,20:00,Premier League,Matchweek 28,Thu,Away,L,0.0,1.0,Brighton,...,5.0,18.5,0.0,0.0,2023,Manchester United,0,4,14,0
139,2023-05-07,19:00,Premier League,Matchweek 35,Sun,Away,L,0.0,1.0,West Ham,...,4.0,18.2,0.0,0.0,2023,Manchester United,0,23,14,0
140,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,W,2.0,0.0,Wolves,...,9.0,19.3,0.0,0.0,2023,Manchester United,1,24,14,1

Calculating rolling averages for columns for the last 3 games.

In [35]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [36]:
cols = ["gf", "ga"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,pk,pkatt,season,club,venue_code,opp_code,club_code,target,gf_rolling,ga_rolling
1382,2020-10-17,20:00,Premier League,Matchweek 5,Sat,Away,W,4.0,1.0,Newcastle Utd,...,0.0,1.0,2021,Manchester United,0,15,14,1,1.666667,3.666667
1383,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Home,D,0.0,0.0,Chelsea,...,0.0,0.0,2021,Manchester United,1,6,14,0,2.666667,3.000000
1384,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Home,L,0.0,1.0,Arsenal,...,0.0,0.0,2021,Manchester United,1,0,14,0,1.666667,2.333333
1385,2020-11-07,12:30,Premier League,Matchweek 8,Sat,Away,W,3.0,1.0,Everton,...,0.0,0.0,2021,Manchester United,0,8,14,1,1.333333,0.666667
1386,2020-11-21,20:00,Premier League,Matchweek 9,Sat,Home,W,1.0,0.0,West Brom,...,1.0,1.0,2021,Manchester United,1,22,14,1,1.000000,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,2023-04-27,20:15,Premier League,Matchweek 33,Thu,Away,D,2.0,2.0,Tottenham,...,0.0,0.0,2023,Manchester United,0,20,14,0,1.666667,0.000000
137,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Home,W,1.0,0.0,Aston Villa,...,0.0,0.0,2023,Manchester United,1,1,14,1,2.000000,0.666667
138,2023-05-04,20:00,Premier League,Matchweek 28,Thu,Away,L,0.0,1.0,Brighton,...,0.0,0.0,2023,Manchester United,0,4,14,0,1.666667,0.666667
139,2023-05-07,19:00,Premier League,Matchweek 35,Sun,Away,L,0.0,1.0,West Ham,...,0.0,0.0,2023,Manchester United,0,23,14,0,1.000000,1.000000
140,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,W,2.0,0.0,Wolves,...,0.0,0.0,2023,Manchester United,1,24,14,1,0.333333,0.666667

In [37]:
matches_rolling = matches_df.groupby("club").apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling

                                   date   time            comp         round  \
club
Arsenal                 1610 2020-10-04  14:00  Premier League   Matchweek 4
                        1611 2020-10-17  17:30  Premier League   Matchweek 5
                        1612 2020-10-25  19:15  Premier League   Matchweek 6
                        1613 2020-11-01  16:30  Premier League   Matchweek 7
                        1614 2020-11-08  19:15  Premier League   Matchweek 8
...                                 ...    ...             ...           ...
Wolverhampton Wanderers 456  2023-04-22  15:00  Premier League  Matchweek 32
                        457  2023-04-25  19:30  Premier League  Matchweek 33
                        458  2023-04-29  15:00  Premier League  Matchweek 34
                        459  2023-05-06  15:00  Premier League  Matchweek 35
                        460  2023-05-13  15:00  Premier League  Matchweek 36

                              day venue result   gf   ga         opponent  \
club
Arsenal                 1610  Sun  Home      W  2.0  1.0    Sheffield Utd
                        1611  Sat  Away      L  0.0  1.0  Manchester City
                        1612  Sun  Home      L  0.0  1.0   Leicester City
                        1613  Sun  Away      W  1.0  0.0   Manchester Utd
                        1614  Sun  Home      L  0.0  3.0      Aston Villa
...                           ...   ...    ...  ...  ...              ...
Wolverhampton Wanderers 456   Sat  Away      L  1.0  2.0   Leicester City
                        457   Tue  Home      W  2.0  0.0   Crystal Palace
                        458   Sat  Away      L  0.0  6.0         Brighton
                        459   Sat  Home      W  1.0  0.0      Aston Villa
                        460   Sat  Away      L  0.0  2.0   Manchester Utd

                              ...   pk  pkatt  season  \
club                          ...
Arsenal                 1610  ...  0.0    0.0    2021
                        1611  ...  0.0    0.0    2021
                        1612  ...  0.0    0.0    2021
                        1613  ...  1.0    1.0    2021
                        1614  ...  0.0    0.0    2021
...                           ...  ...    ...     ...
Wolverhampton Wanderers 456   ...  0.0    0.0    2023
                        457   ...  1.0    1.0    2023
                        458   ...  0.0    0.0    2023
                        459   ...  0.0    0.0    2023
                        460   ...  0.0    0.0    2023

                                                 club venue_code opp_code  \
club
Arsenal                 1610                  Arsenal          1       18
                        1611                  Arsenal          0       13
                        1612                  Arsenal          1       11
                        1613                  Arsenal          0       14
                        1614                  Arsenal          1        1
...                                               ...        ...      ...
Wolverhampton Wanderers 456   Wolverhampton Wanderers          0       11
                        457   Wolverhampton Wanderers          1        7
                        458   Wolverhampton Wanderers          0        4
                        459   Wolverhampton Wanderers          1        1
                        460   Wolverhampton Wanderers          0       14

                             club_code target  gf_rolling  ga_rolling
club
Arsenal                 1610         0      1    2.000000    1.333333
                        1611         0      0    1.666667    1.666667
                        1612         0      0    1.000000    1.666667
                        1613         0      1    0.666667    1.000000
                        1614         0      0    0.333333    0.666667
...                                ...    ...         ...         ...
Wolverhampton Wanderers 456         24      0    1.333333    0.333333
                        457         24      1    1.333333    0.666667
                        458         24      0    1.666667    0.666667
                        459         24      1    1.000000    2.666667
                        460         24      0    1.000000    2.000000

[2026 rows x 32 columns]

In [38]:
matches_rolling = matches_rolling.droplevel("club")

In [39]:
matches_rolling.index = range(matches_rolling.shape[0])

In [40]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,pk,pkatt,season,club,venue_code,opp_code,club_code,target,gf_rolling,ga_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,0.0,0.0,2021,Arsenal,1,18,0,1,2.000000,1.333333
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,0.0,0.0,2021,Arsenal,0,13,0,0,1.666667,1.666667
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,0.0,0.0,2021,Arsenal,1,11,0,0,1.000000,1.666667
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,1.0,1.0,2021,Arsenal,0,14,0,1,0.666667,1.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,0.0,0.0,2021,Arsenal,1,1,0,0,0.333333,0.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021,2023-04-22,15:00,Premier League,Matchweek 32,Sat,Away,L,1.0,2.0,Leicester City,...,0.0,0.0,2023,Wolverhampton Wanderers,0,11,24,0,1.333333,0.333333
2022,2023-04-25,19:30,Premier League,Matchweek 33,Tue,Home,W,2.0,0.0,Crystal Palace,...,1.0,1.0,2023,Wolverhampton Wanderers,1,7,24,1,1.333333,0.666667
2023,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0.0,6.0,Brighton,...,0.0,0.0,2023,Wolverhampton Wanderers,0,4,24,0,1.666667,0.666667
2024,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1.0,0.0,Aston Villa,...,0.0,0.0,2023,Wolverhampton Wanderers,1,1,24,1,1.000000,2.666667
2025,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0.0,2.0,Manchester Utd,...,0.0,0.0,2023,Wolverhampton Wanderers,0,14,24,0,1.000000,2.000000

In [41]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-01-01']
    test = data[data["date"] > '2023-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [42]:
combined, precision_rf = make_predictions(matches_rolling, predictors+new_cols)

In [43]:
precision_rf

0.5604395604395604

In [44]:
combined = combined.merge(matches_rolling[["date", "club", "opponent", "result"]], left_index=True, right_index=True)

In [45]:
combined

,actual,predicted,date,club,opponent,result
84,0,1,2023-01-03,Arsenal,Newcastle Utd,D
85,1,1,2023-01-15,Arsenal,Tottenham,W
86,1,0,2023-01-22,Arsenal,Manchester Utd,W
87,0,1,2023-02-04,Arsenal,Everton,L
88,0,1,2023-02-11,Arsenal,Brentford,D
...,...,...,...,...,...,...
2021,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L
2022,1,1,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W
2023,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L
2024,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W
2025,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L

In [46]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

combined["new_club"] = combined["club"].map(mapping)

In [47]:
combined

,actual,predicted,date,club,opponent,result,new_club
84,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal
85,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal
86,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal
87,0,1,2023-02-04,Arsenal,Everton,L,Arsenal
88,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal
...,...,...,...,...,...,...,...
2021,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L,Wolves
2022,1,1,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W,Wolves
2023,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
2024,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves
2025,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves

In [48]:
merged = combined.merge(combined, left_on=["date", "new_club"], right_on=["date", "opponent"])
merged

,actual_x,predicted_x,date,club_x,opponent_x,result_x,new_club_x,actual_y,predicted_y,club_y,opponent_y,result_y,new_club_y
0,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
2,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,0,Manchester United,Arsenal,L,Manchester Utd
3,0,1,2023-02-04,Arsenal,Everton,L,Arsenal,1,0,Everton,Arsenal,W,Everton
4,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal,0,0,Brentford,Arsenal,D,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L,Wolves,1,0,Leicester City,Wolves,W,Leicester City
357,1,1,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W,Wolves,0,1,Crystal Palace,Wolves,L,Crystal Palace
358,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,0,Brighton and Hove Albion,Wolves,W,Brighton
359,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
360,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,1,Manchester United,Wolves,W,Manchester Utd

## XGBoost

In [49]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

In [50]:
xgb = XGBClassifier(objective='binary:logistic', nthread=4, seed=42)

In [51]:
train = matches_rolling[matches_rolling["date"] < '2023-01-01']
test = matches_rolling[matches_rolling["date"] > '2023-01-01']

In [52]:
xgb.fit(train[predictors+new_cols], train["target"])

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, nthread=4, num_parallel_tree=None,
              predictor=None, ...)

In [53]:
pred_xgb = xgb.predict(test[predictors+new_cols])

In [54]:
precision_xgb = precision_score(test["target"], pred_xgb)
print(f"XGBoost Precision: {precision_xgb} Random Forest Precision: {precision_rf}")

XGBoost Precision: 0.5230769230769231 Random Forest Precision: 0.5604395604395604

In [58]:
matches_rolling[["club", "club_code"]].value_counts()

club                      club_code
West Ham United           23           105
Southampton               19           105
Arsenal                   0            104
Leeds United              10           104
Tottenham Hotspur         20           104
Newcastle United          15           104
Manchester United         14           104
Wolverhampton Wanderers   24           104
Crystal Palace            7            104
Everton                   8            103
Aston Villa               1            103
Manchester City           13           103
Brighton and Hove Albion  4            103
Leicester City            11           102
Chelsea                   6            102
Fulham                    9             71
Liverpool                 12            70
Burnley                   5             68
Brentford                 3             67
Sheffield United          18            35
West Bromwich Albion      22            35
Nottingham Forest         17            33
Bournemouth               2             33
Watford                   21            30
Norwich City              16            30
dtype: int64

In [59]:
predictors+new_cols

['venue_code', 'opp_code', 'club_code', 'gf_rolling', 'ga_rolling']

In [61]:
input_df = pd.DataFrame({
    'venue_code':[1], 'opp_code':[1], 'club_code':[11], 'gf_rolling':[5], 'ga_rolling':[3]
})

In [63]:
xgb.predict(input_df)

array([0])

### Logistic Regression Model

In [99]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBClassifier
from sklearn.metrics import r2_score,mean_absolute_error
from sklearn.linear_model import LogisticRegression

In [85]:
matches_rolling.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,pk,pkatt,season,club,venue_code,opp_code,club_code,target,gf_rolling,ga_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,0.0,0.0,2021,Arsenal,1,18,0,1,2.000000,1.333333
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,0.0,0.0,2021,Arsenal,0,13,0,0,1.666667,1.666667
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,0.0,0.0,2021,Arsenal,1,11,0,0,1.000000,1.666667
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,1.0,1.0,2021,Arsenal,0,14,0,1,0.666667,1.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,0.0,0.0,2021,Arsenal,1,1,0,0,0.333333,0.666667

In [86]:
X = matches_rolling[['venue', 'club', 'opponent', 'gf_rolling', 'ga_rolling']]
y = matches_rolling['target']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [87]:
X_train

     venue                     club         opponent  gf_rolling  ga_rolling
165   Away              Aston Villa     Leeds United    2.000000    0.333333
1325  Away        Manchester United          Arsenal    2.000000    0.666667
948   Away             Leeds United          Everton    0.666667    1.666667
49    Away                  Arsenal          Everton    1.333333    2.333333
1084  Away                Liverpool   Leicester City    1.333333    2.000000
...    ...                      ...              ...         ...         ...
1791  Away     West Bromwich Albion  Manchester City    1.000000    2.333333
1096  Away                Liverpool        West Brom    2.333333    1.000000
1932  Away  Wolverhampton Wanderers          Burnley    0.666667    2.000000
235   Home              Bournemouth         West Ham    1.333333    1.333333
1061  Away           Leicester City     Leeds United    1.000000    1.666667

[1620 rows x 5 columns]

In [120]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['venue','club','opponent'])
]
,remainder='passthrough')

In [121]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',LogisticRegression(solver='liblinear'))
])

In [122]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(precision_score(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

-0.4816761943650476
0.3522167487684729
0.5773195876288659
0.6477832512315271

In [123]:
input_df = pd.DataFrame({
    'club': ['Watford'], 'opponent': ['Manchester City'], 'venue': ['Home'], 'gf_rolling':[5], 'ga_rolling':[3]
})

In [127]:
pipe.predict_proba(input_df)[0][1] * 100

4.048487600459099

In [128]:
import pickle

In [129]:
pickle.dump(pipe, open('pipe.pkl', 'wb'))

In [141]:
X_train['club'].unique()

array(['Aston Villa', 'Manchester United', 'Leeds United', 'Arsenal',
       'Liverpool', 'Chelsea', 'West Ham United', 'Crystal Palace',
       'Tottenham Hotspur', 'Southampton', 'Newcastle United',
       'Sheffield United', 'Fulham', 'Brighton and Hove Albion',
       'Norwich City', 'Leicester City', 'Manchester City',
       'Wolverhampton Wanderers', 'Brentford', 'Nottingham Forest',
       'Burnley', 'Everton', 'Bournemouth', 'West Bromwich Albion',
       'Watford'], dtype=object)