In [1]:
import pandas as pd

In [2]:
matches_df = pd.read_csv("data_final.csv")

In [3]:
matches_df.head()

,Unnamed: 0,date,time,comp,round,day,venue,result,gf,ga,...,referee,match report,notes,sh,sot,dist,pk,pkatt,season,club
0,1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,...,Michael Oliver,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,2023,Manchester-City
1,2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,...,David Coote,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,2023,Manchester-City
2,3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,...,Jarred Gillett,Match Report,NaN,21.0,10.0,16.2,0.0,0.0,2023,Manchester-City
3,4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,...,Darren England,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,2023,Manchester-City
4,5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,...,Paul Tierney,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,2023,Manchester-City

In [4]:
matches_df.shape

(2101, 27)

In [5]:
matches_df["club"].value_counts()

Southampton                 108
Arsenal                     107
Everton                     106
Chelsea                     105
Fulham                       74
Liverpool                    73
Newcastle United             72
West Ham United              72
Manchester United            72
Brighton and Hove Albion     72
Leeds United                 71
Burnley                      71
Wolverhampton Wanderers      71
Tottenham Hotspur            71
Manchester City              71
Crystal Palace               71
Leicester City               70
Brentford                    70
Aston Villa                  70
Sheffield United             38
West Bromwich Albion         38
Leeds-United                 36
Nottingham-Forest            36
Bournemouth                  36
Wolverhampton-Wanderers      36
Crystal-Palace               36
Aston-Villa                  36
Tottenham-Hotspur            36
West-Ham-United              36
Manchester-City              35
Manchester-United            35
Newcastle-United             35
Leicester-City               35
Brighton-and-Hove-Albion     34
Watford                      33
Norwich City                 33
Name: club, dtype: int64

In [6]:
for i in range(2101):
    name = matches_df[matches_df.columns[-1]][i]
    name = " ".join(name.split("-"))
    matches_df.replace(to_replace = matches_df[matches_df.columns[-1]][i], value = name, inplace = True)

In [7]:
matches_df["club"].value_counts()

Southampton                 108
West Ham United             108
Wolverhampton Wanderers     107
Crystal Palace              107
Newcastle United            107
Manchester United           107
Leeds United                107
Tottenham Hotspur           107
Arsenal                     107
Everton                     106
Manchester City             106
Aston Villa                 106
Brighton and Hove Albion    106
Chelsea                     105
Leicester City              105
Fulham                       74
Liverpool                    73
Burnley                      71
Brentford                    70
West Bromwich Albion         38
Sheffield United             38
Bournemouth                  36
Nottingham Forest            36
Watford                      33
Norwich City                 33
Name: club, dtype: int64

In [8]:
matches_df.dtypes

Unnamed: 0        int64
date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
pk              float64
pkatt           float64
season            int64
club             object
dtype: object

In [9]:
matches_df["date"] = pd.to_datetime(matches_df["date"])

In [10]:
matches_df.dtypes

Unnamed: 0               int64
date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
pk                     float64
pkatt                  float64
season                   int64
club                    object
dtype: object

In [11]:
matches_df["venue_code"] = matches_df["venue"].astype("category").cat.codes

In [12]:
matches_df["opp_code"] = matches_df["opponent"].astype("category").cat.codes

In [13]:
matches_df["hour"] = matches_df["time"].str.replace(":.+", "", regex=True).astype("int")

In [14]:
matches_df["day_code"] = matches_df["date"].dt.dayofweek

In [15]:
matches_df["target"] = (matches_df["result"] == "W").astype("int")

In [16]:
matches_df.drop(matches_df.columns[[0]], axis = 1, inplace = True)

In [17]:
matches_df.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,pk,pkatt,season,club,venue_code,opp_code,hour,day_code,target
0,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2.0,0.0,West Ham,...,18.7,1.0,1.0,2023,Manchester City,0,23,16,6,1
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4.0,0.0,Bournemouth,...,17.5,0.0,0.0,2023,Manchester City,1,2,15,5,1
2,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3.0,3.0,Newcastle Utd,...,16.2,0.0,0.0,2023,Manchester City,0,15,16,6,0
3,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,2.0,Crystal Palace,...,14.1,0.0,0.0,2023,Manchester City,1,7,15,5,1
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6.0,0.0,Nott'ham Forest,...,14.8,0.0,0.0,2023,Manchester City,1,17,19,2,1

In [18]:
matches_df.isna().sum()

date               0
time               0
comp               0
round              0
day                0
venue              0
result             0
gf                 0
ga                 0
opponent           0
xg                 0
xga                0
poss               0
attendance       700
captain            0
formation          0
referee            0
match report       0
notes           2101
sh                 0
sot                0
dist               1
pk                 0
pkatt              0
season             0
club               0
venue_code         0
opp_code           0
hour               0
day_code           0
target             0
dtype: int64

## Random Forest Algorithm

In [60]:
from sklearn.ensemble import RandomForestClassifier

In [61]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [62]:
train = matches_df[matches_df["date"] < '2023-01-01']

In [63]:
test = matches_df[matches_df["date"] > '2023-01-01']

In [64]:
predictors = ["venue_code", "opp_code", "hour", "day_code", "xg", "xga", "poss"]

In [65]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [66]:
predictions = rf.predict(test[predictors])

In [67]:
from sklearn.metrics import accuracy_score

In [68]:
accuracy_score(test["target"], predictions)

0.7210526315789474

In [69]:
combined_df = pd.DataFrame(dict(actual=test["target"], prediction=predictions))

In [70]:
pd.crosstab(index=combined_df["actual"], columns=combined_df["prediction"])

prediction    0   1
actual
0           185  46
1            60  89

In [71]:
from sklearn.metrics import precision_score

In [72]:
precision_score(test["target"], predictions)

0.6592592592592592

In [73]:
grouped_matches = matches_df.groupby("club")

In [74]:
group = grouped_matches.get_group("Manchester United").sort_values("date")

In [75]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,dist,pk,pkatt,season,club,venue_code,opp_code,hour,day_code,target
1379,2020-09-19,17:30,Premier League,Matchweek 2,Sat,Home,L,1.0,3.0,Crystal Palace,...,18.9,0.0,0.0,2021,Manchester United,1,7,17,5,0
1380,2020-09-26,12:30,Premier League,Matchweek 3,Sat,Away,W,3.0,2.0,Brighton,...,17.8,1.0,1.0,2021,Manchester United,0,4,12,5,1
1381,2020-10-04,16:30,Premier League,Matchweek 4,Sun,Home,L,1.0,6.0,Tottenham,...,22.7,1.0,1.0,2021,Manchester United,1,20,16,6,0
1382,2020-10-17,20:00,Premier League,Matchweek 5,Sat,Away,W,4.0,1.0,Newcastle Utd,...,19.5,0.0,1.0,2021,Manchester United,0,15,20,5,1
1383,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Home,D,0.0,0.0,Chelsea,...,16.9,0.0,0.0,2021,Manchester United,1,6,17,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,2023-04-27,20:15,Premier League,Matchweek 33,Thu,Away,D,2.0,2.0,Tottenham,...,17.9,0.0,0.0,2023,Manchester United,0,20,20,3,0
137,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Home,W,1.0,0.0,Aston Villa,...,19.0,0.0,0.0,2023,Manchester United,1,1,14,6,1
138,2023-05-04,20:00,Premier League,Matchweek 28,Thu,Away,L,0.0,1.0,Brighton,...,18.5,0.0,0.0,2023,Manchester United,0,4,20,3,0
139,2023-05-07,19:00,Premier League,Matchweek 35,Sun,Away,L,0.0,1.0,West Ham,...,18.2,0.0,0.0,2023,Manchester United,0,23,19,6,0
140,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,W,2.0,0.0,Wolves,...,19.3,0.0,0.0,2023,Manchester United,1,24,15,5,1

In [76]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [77]:
cols = ["gf", "ga", "sh", "sot", "dist", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,pk_rolling,pkatt_rolling
1382,2020-10-17,20:00,Premier League,Matchweek 5,Sat,Away,W,4.0,1.0,Newcastle Utd,...,20,5,1,1.666667,3.666667,9.000000,2.333333,19.800000,0.666667,0.666667
1383,2020-10-24,17:30,Premier League,Matchweek 6,Sat,Home,D,0.0,0.0,Chelsea,...,17,5,0,2.666667,3.000000,12.333333,4.666667,20.000000,0.666667,1.000000
1384,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Home,L,0.0,1.0,Arsenal,...,16,6,0,1.666667,2.333333,15.000000,5.333333,19.700000,0.333333,0.666667
1385,2020-11-07,12:30,Premier League,Matchweek 8,Sat,Away,W,3.0,1.0,Everton,...,12,5,1,1.333333,0.666667,16.666667,5.666667,18.300000,0.000000,0.333333
1386,2020-11-21,20:00,Premier League,Matchweek 9,Sat,Home,W,1.0,0.0,West Brom,...,20,5,1,1.000000,0.666667,12.000000,3.666667,18.733333,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,2023-04-27,20:15,Premier League,Matchweek 33,Thu,Away,D,2.0,2.0,Tottenham,...,20,3,0,1.666667,0.000000,23.000000,7.000000,17.266667,0.000000,0.000000
137,2023-04-30,14:00,Premier League,Matchweek 34,Sun,Home,W,1.0,0.0,Aston Villa,...,14,6,1,2.000000,0.666667,22.666667,8.333333,16.600000,0.000000,0.000000
138,2023-05-04,20:00,Premier League,Matchweek 28,Thu,Away,L,0.0,1.0,Brighton,...,20,3,0,1.666667,0.666667,17.666667,6.666667,17.433333,0.000000,0.000000
139,2023-05-07,19:00,Premier League,Matchweek 35,Sun,Away,L,0.0,1.0,West Ham,...,19,6,0,1.000000,1.000000,15.666667,6.000000,18.466667,0.000000,0.000000
140,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Home,W,2.0,0.0,Wolves,...,15,5,1,0.333333,0.666667,16.333333,5.000000,18.566667,0.000000,0.000000

In [78]:
matches_rolling = matches_df.groupby("club").apply(lambda x: rolling_averages(x, cols, new_cols))
matches_rolling

                                   date   time            comp         round  \
club
Arsenal                 1610 2020-10-04  14:00  Premier League   Matchweek 4
                        1611 2020-10-17  17:30  Premier League   Matchweek 5
                        1612 2020-10-25  19:15  Premier League   Matchweek 6
                        1613 2020-11-01  16:30  Premier League   Matchweek 7
                        1614 2020-11-08  19:15  Premier League   Matchweek 8
...                                 ...    ...             ...           ...
Wolverhampton Wanderers 456  2023-04-22  15:00  Premier League  Matchweek 32
                        457  2023-04-25  19:30  Premier League  Matchweek 33
                        458  2023-04-29  15:00  Premier League  Matchweek 34
                        459  2023-05-06  15:00  Premier League  Matchweek 35
                        460  2023-05-13  15:00  Premier League  Matchweek 36

                              day venue result   gf   ga         opponent  \
club
Arsenal                 1610  Sun  Home      W  2.0  1.0    Sheffield Utd
                        1611  Sat  Away      L  0.0  1.0  Manchester City
                        1612  Sun  Home      L  0.0  1.0   Leicester City
                        1613  Sun  Away      W  1.0  0.0   Manchester Utd
                        1614  Sun  Home      L  0.0  3.0      Aston Villa
...                           ...   ...    ...  ...  ...              ...
Wolverhampton Wanderers 456   Sat  Away      L  1.0  2.0   Leicester City
                        457   Tue  Home      W  2.0  0.0   Crystal Palace
                        458   Sat  Away      L  0.0  6.0         Brighton
                        459   Sat  Home      W  1.0  0.0      Aston Villa
                        460   Sat  Away      L  0.0  2.0   Manchester Utd

                              ...  hour  day_code  target  gf_rolling  \
club                          ...
Arsenal                 1610  ...    14         6       1    2.000000
                        1611  ...    17         5       0    1.666667
                        1612  ...    19         6       0    1.000000
                        1613  ...    16         6       1    0.666667
                        1614  ...    19         6       0    0.333333
...                           ...   ...       ...     ...         ...
Wolverhampton Wanderers 456   ...    15         5       0    1.333333
                        457   ...    19         1       1    1.333333
                        458   ...    15         5       0    1.666667
                        459   ...    15         5       1    1.000000
                        460   ...    15         5       0    1.000000

                             ga_rolling sh_rolling sot_rolling dist_rolling  \
club
Arsenal                 1610   1.333333   7.666667    3.666667    14.733333
                        1611   1.666667   5.333333    3.666667    15.766667
                        1612   1.666667   7.000000    3.666667    16.733333
                        1613   1.000000   9.666667    4.000000    16.033333
                        1614   0.666667   9.666667    2.666667    18.033333
...                                 ...        ...         ...          ...
Wolverhampton Wanderers 456    0.333333   9.333333    4.666667    19.933333
                        457    0.666667  12.000000    5.333333    21.100000
                        458    0.666667  11.666667    4.666667    18.700000
                        459    2.666667  11.333333    2.333333    18.800000
                        460    2.000000   8.000000    2.000000    17.766667

                              pk_rolling  pkatt_rolling
club
Arsenal                 1610    0.000000       0.000000
                        1611    0.000000       0.000000
                        1612    0.000000       0.000000
                        1613    0.000000       0.000000
                        1614    0.333333       0.333333
...                                  ...            ...
Wolverhampton Wanderers 456     0.000000       0.000000
                        457     0.000000       0.000000
                        458     0.333333       0.333333
                        459     0.333333       0.333333
                        460     0.333333       0.333333

[2023 rows x 38 columns]

In [79]:
matches_rolling = matches_rolling.droplevel("club")

In [80]:
matches_rolling.index = range(matches_rolling.shape[0])

In [81]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,hour,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2.0,1.0,Sheffield Utd,...,14,6,1,2.000000,1.333333,7.666667,3.666667,14.733333,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0.0,1.0,Manchester City,...,17,5,0,1.666667,1.666667,5.333333,3.666667,15.766667,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0.0,1.0,Leicester City,...,19,6,0,1.000000,1.666667,7.000000,3.666667,16.733333,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1.0,0.0,Manchester Utd,...,16,6,1,0.666667,1.000000,9.666667,4.000000,16.033333,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0.0,3.0,Aston Villa,...,19,6,0,0.333333,0.666667,9.666667,2.666667,18.033333,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018,2023-04-22,15:00,Premier League,Matchweek 32,Sat,Away,L,1.0,2.0,Leicester City,...,15,5,0,1.333333,0.333333,9.333333,4.666667,19.933333,0.000000,0.000000
2019,2023-04-25,19:30,Premier League,Matchweek 33,Tue,Home,W,2.0,0.0,Crystal Palace,...,19,1,1,1.333333,0.666667,12.000000,5.333333,21.100000,0.000000,0.000000
2020,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0.0,6.0,Brighton,...,15,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.333333,0.333333
2021,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1.0,0.0,Aston Villa,...,15,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.333333,0.333333
2022,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0.0,2.0,Manchester Utd,...,15,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.333333,0.333333

In [82]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-01-01']
    test = data[data["date"] > '2023-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision = precision_score(test["target"], preds)
    return combined, precision

In [83]:
combined, precision = make_predictions(matches_rolling, predictors+new_cols)

In [84]:
precision

0.6747967479674797

In [85]:
combined = combined.merge(matches_rolling[["date", "club", "opponent", "result"]], left_index=True, right_index=True)

In [86]:
combined

,actual,predicted,date,club,opponent,result
84,0,0,2023-01-03,Arsenal,Newcastle Utd,D
85,1,1,2023-01-15,Arsenal,Tottenham,W
86,1,1,2023-01-22,Arsenal,Manchester Utd,W
87,0,0,2023-02-04,Arsenal,Everton,L
88,0,0,2023-02-11,Arsenal,Brentford,D
...,...,...,...,...,...,...
2018,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L
2019,1,0,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W
2020,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L
2021,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W
2022,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L

In [87]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

combined["new_club"] = combined["club"].map(mapping)

In [88]:
combined

,actual,predicted,date,club,opponent,result,new_club
84,0,0,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal
85,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal
86,1,1,2023-01-22,Arsenal,Manchester Utd,W,Arsenal
87,0,0,2023-02-04,Arsenal,Everton,L,Arsenal
88,0,0,2023-02-11,Arsenal,Brentford,D,Arsenal
...,...,...,...,...,...,...,...
2018,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L,Wolves
2019,1,0,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W,Wolves
2020,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
2021,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves
2022,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves

In [89]:
merged = combined.merge(combined, left_on=["date", "new_club"], right_on=["date", "opponent"])
merged

,actual_x,predicted_x,date,club_x,opponent_x,result_x,new_club_x,actual_y,predicted_y,club_y,opponent_y,result_y,new_club_y
0,0,0,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,1,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
2,1,1,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,0,Manchester United,Arsenal,L,Manchester Utd
3,0,0,2023-02-04,Arsenal,Everton,L,Arsenal,1,0,Everton,Arsenal,W,Everton
4,0,0,2023-02-11,Arsenal,Brentford,D,Arsenal,0,1,Brentford,Arsenal,D,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
356,0,0,2023-04-22,Wolverhampton Wanderers,Leicester City,L,Wolves,1,1,Leicester City,Wolves,W,Leicester City
357,1,0,2023-04-25,Wolverhampton Wanderers,Crystal Palace,W,Wolves,0,0,Crystal Palace,Wolves,L,Crystal Palace
358,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
359,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
360,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,1,Manchester United,Wolves,W,Manchester Utd